clone_depth: 10
skip_tags: true

init:
  - git config --global core.autocrlf input

branches:
  only:
    - deploy



cache:
  - "node_modules -> package.json"
  - "src\\node_modules -> src\\package.json"
  - "cache -> src\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - npm install -g npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g gulp
  - npm install

before_build:
  - npm test
  - gulp rebuild:32 --verbose
 






